	TransitionMatrixF		   = new double[iM*iM];	MeasureS_Summ			 = new double[3];
	CovarianceMatrixS_minus    = new double[iM*iM];	ConditionVector_minus    = new double[iM];		
	StringOfMeasureH		   = new double[iM];	W_s_Summ				 = new double[3];
    KalmanMatrixA			   = new double[iM*iM];	KalmFactor			     = new double[iM];	
	A_x0s					   = new double[3*3];	W_s_prev				 = new double[3];
    KalmanMatrixH			   = new double[iM*iMz];MeasureS_prev			 = new double[3];
	ConditionVector_plus	   = new double[iM];
	CovarianceMatrixS_plus	   = new double[iM*iM]; A_xs					 = new double[3*3];
	MeasureS				   = new double[3];	
	MeasureX				   = new double[3];	
	W_s						   = new double[3];		Temp1				     = new double[3];
	A_sx0					   = new double[3*3];	Temp2				     = new double[3];
	MeasureS_Average		   = new double[3];
	A_etaX0					   = new double[9];		A_sKsi					 = new double[9];	

    NullingOfArray(iM*iM, KalmanMatrixA);		       
	NullingOfArray(iM*iM, CovarianceMatrixS_plus);
    NullingOfArray(iM*iM, CovarianceMatrixS_minus);   
    NullingOfArray(iM*iM, TransitionMatrixF);	       
	NullingOfArray(iM, ConditionVector_plus);
    NullingOfArray(iM*iMz, KalmanMatrixH);
	NullingOfArray(iM, ConditionVector_minus);
	NullingOfArray(iM, KalmFactor);
	NullingOfArray(iM, StringOfMeasureH);
	NullingOfArray(3, MeasureS);
	NullingOfArray(3, MeasureX);
	NullingOfArray(3*3, A_x0s);
	NullingOfArray(3*3, A_sx0);
	NullingOfArray(3*3, A_xs);
	NullingOfArray(3, Temp1);
	NullingOfArray(3, Temp2);
	NullingOfArray(3, MeasureS_Summ);
	NullingOfArray(3, W_s_Summ);
	NullingOfArray(3, W_s);

	CovarianceMatrixNoise      = new double[iM*iMq];
	NullingOfArray(iM*iMq, CovarianceMatrixNoise);